name: sass_language_services
description: Language service features for Sass.
version: 1.0.0
repository: https://github.com/sass/sass_language_server/pkgs/sass_language_services
resolution: workspace

environment:
  sdk: ^3.5.3

dependencies:
  lsp_server: ^0.3.2
  path: ^1.9.0
  sass_api: ^14.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  sass_analysis:
    git: { url: https://github.com/sass/dart-sass.git, path: analysis }
