name: sass_language_services
description: Language service features for Sass.
version: 1.0.0
repository: https://github.com/wkillerud/sass_language_server/pkgs/sass_language_services

environment:
  sdk: ^3.5.3

dependencies:
  intl: ^0.19.0
  lsp_server: ^0.3.2
  path: ^1.9.0
  sass_api: ^12.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
