name: sass_language_server
description: Language server for Sass using the Language Server Protocol (LSP).
version: 1.0.0
repository: https://github.com/wkillerud/sass_language_server/pkgs/sass_language_server

environment:
  sdk: ^3.5.3

dependencies:
  sass_language_services: ^1.0.0
  lsp_server: ^0.3.2
  glob: ^2.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
